# Generated by Django 5.0.6 on 2026-09-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='actif',
            field=models.BooleanField(default=True, help_text='Compte actif ou désactivé'),
        ),
        migrations.AddField(
            model_name='user',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('voyant', 'Voyant'), ('responsable', 'Responsable'), ('admin', 'Administrateur')], default='voyant', max_length=20),
        ),
    ]
