# Generated by Django 5.0.6 on 2026-09-22 20:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('A', 'Autre')], max_length=1)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('lieu_naissance', models.CharField(blank=True, max_length=200)),
                ('signe_astrologique', models.CharField(blank=True, max_length=50)),
                ('chemin_de_vie', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('annee_personnelle', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('chiffre_cle', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('situation_familiale', models.CharField(blank=True, max_length=100)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('nombre_enfants', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('description_generale', models.TextField(blank=True, help_text='Qui est ce client ? Son histoire, son caractère...')),
                ('forfait', models.CharField(blank=True, help_text="Ex: 'Forfait Premium 50€', 'Pack découverte', etc.", max_length=200)),
                ('forfait_montant', models.DecimalField(blank=True, decimal_places=2, help_text='Montant payé par le client (optionnel)', max_digits=10, null=True)),
                ('forfait_notes', models.CharField(blank=True, max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('couleur', models.CharField(default='#7c3aed', max_length=7)),
                ('favori', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('voyant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-favori', '-modifie_le'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateField(default=datetime.date.today)),
                ('titre', models.CharField(blank=True, help_text="Ex: '1ère consultation', '2ème consultation', laissez vide pour auto", max_length=200)),
                ('notes_generales', models.TextField(blank=True, help_text='Résumé général de la consultation')),
                ('sujet_sentimental', models.TextField(blank=True, help_text="Ce qu'on a abordé côté sentiment/amour")),
                ('sujet_professionnel', models.TextField(blank=True, help_text="Ce qu'on a abordé côté travail/carrière")),
                ('sujet_financier', models.TextField(blank=True, help_text="Ce qu'on a abordé côté argent/finances")),
                ('duree_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='carnet.ficheclient')),
            ],
            options={
                'ordering': ['-date_consultation', '-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_rdv', models.DateField()),
                ('heure_rdv', models.TimeField()),
                ('duree_estimee', models.PositiveIntegerField(default=30, help_text='Durée en minutes')),
                ('mode', models.CharField(choices=[('telephone', 'Téléphone'), ('chat', 'Chat'), ('visio', 'Visioconférence'), ('presentiel', 'Présentiel')], default='telephone', max_length=20)),
                ('sujet_prevu', models.TextField(blank=True, help_text='De quoi va-t-on parler ?')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('confirme', 'Confirmé'), ('termine', 'Terminé'), ('annule', 'Annulé'), ('reporte', 'Reporté')], default='planifie', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='carnet.ficheclient')),
            ],
            options={
                'ordering': ['date_rdv', 'heure_rdv'],
            },
        ),
        migrations.AddIndex(
            model_name='ficheclient',
            index=models.Index(fields=['voyant', '-modifie_le'], name='carnet_fich_voyant__2f5a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='ficheclient',
            index=models.Index(fields=['voyant', 'nom'], name='carnet_fich_voyant__9ece6e_idx'),
        ),
    ]
